### PR TITLE
Updates selectivity version

### PR DESCRIPTION
**Pull request by Tuhaj**
- removes typo
- updates to the new Selectivity 3.0 version
  https://github.com/arendjr/selectivity/releases - the `npm run build-vanilla-source` version of selectivity has been used for the `selectivit.js` file
  Attention, breaking changes

### CODE REVIEW

**Comment by Tuhaj** [comment]
@msx2 I realised that because selectivity has separated the jQuery, react and vanilla versions to different builds this PR should support it. For myself I had to use the jQuery version. I keep this version on a separate branch. Maybe you have an idea how to do that better, so that selectivity-rails asks us for the version needed? https://github.com/arendjr/selectivity/releases/tag/3.0.0

**Comment by msx2** [comment]
Hi @Tuhaj. Thanks for the pull request!

Personally I don't think I will be using this gem with more than (just) jQuery so I'd be perfectly fine with using only this version.
But for convenience I think we could consider including all three combinations in the repository, with different filenames - following the same naming that is mentioned in [Selectivity's README](https://github.com/arendjr/selectivity#manual), i.e.
- `selectivity-jquery`
- `selectivity-react`
- `selectivity` - for Vanilla JS

Unfortunately, since this has always been a jQuery plugin I cannot merge this PR if it doesn't provide a working jQuery version of Selectivity.

## Side note.

If there is a support of all versions in this repository, we need to use `post_install_message` in `selectivity-rails.gemspec` to let users know there were some big changes in the gem, and in Selectivity. Just to avoid confusion when the app stops working. And, of course, it would be a good idea to update gem description as it still mentions jQuery and Zepto.js 😄

**Comment by Tuhaj** [comment]
Hi @msx2 
thanks for fast answer. For now I add then the jQuery version of selectivity, and that’s great because thats also the version I’m using ;-)

**Comment by msx2** [comment]
@Tuhaj Sorry it took so long! Thanks for replacing with jQuery version.

Over the next few days I will try to allow also for React and Vanilla JS versions in gem.

**Comment by Tuhaj** [comment]
Thanks for merging 😄

**Pull request merged**
