### PR TITLE
Update selectivity.js to 3.0.1

### PR DESCRIPTION
**Pull request by Fudoshiki**

### CODE REVIEW

**Comment by msx2** [comment]
Hi @Fudoshiki! Thanks for pull request. Unfortunately it's not a jQuery's version so I can't merge it. For time being this will only contain jQuery version of Selectivity. Or in the later step (or if somebody beats me to it), all supported versions which is Vanilla JS, jQuery and React.

**Comment by Fudoshiki** [comment]
Can I add all versions with update README.md in current PR?

**Comment by msx2** [comment]
Feel free to do so. 😄  BUT, if you change the default behavior (`selectivity.js` not being jQuery version) you need to also add `post_install_message` to `selectivity-rails.gemspec` to let everyone know that defaults (and therefore behavior) have changed. Would be also good to change gemspec description when adding new versions 😉

**Comment by Fudoshiki** [comment]
Ok) will do

**Pull request closed without merging**
